// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA00qS_bq0DaWS9uw76DV4fkUlxGuhOjVM',
    appId: '1:808439838248:web:f903b84fe299f711dd671d',
    messagingSenderId: '808439838248',
    projectId: 'budgetbuddy-705f7',
    authDomain: 'budgetbuddy-705f7.firebaseapp.com',
    storageBucket: 'budgetbuddy-705f7.appspot.com',
    measurementId: 'G-CFLKD8KJV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA6aCUgwb2eKfBFs4-LV3aL5B27bt7S1I',
    appId: '1:808439838248:android:1b89b98afc795be2dd671d',
    messagingSenderId: '808439838248',
    projectId: 'budgetbuddy-705f7',
    storageBucket: 'budgetbuddy-705f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY5zlnkUdy4LkpqIA7VwQwtvgPtp7GCz4',
    appId: '1:808439838248:ios:accf4fc71693f77add671d',
    messagingSenderId: '808439838248',
    projectId: 'budgetbuddy-705f7',
    storageBucket: 'budgetbuddy-705f7.appspot.com',
    iosBundleId: 'com.example.budgetbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY5zlnkUdy4LkpqIA7VwQwtvgPtp7GCz4',
    appId: '1:808439838248:ios:116a2e518b4d2ae4dd671d',
    messagingSenderId: '808439838248',
    projectId: 'budgetbuddy-705f7',
    storageBucket: 'budgetbuddy-705f7.appspot.com',
    iosBundleId: 'com.example.budgetbuddy.RunnerTests',
  );
}
